// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX1r7MaygmY_uhch0CnOKYfh6HkEB20iU',
    appId: '1:600457489084:web:d95b47aa3f6fda5e927eb9',
    messagingSenderId: '600457489084',
    projectId: 'contacts-app-6ea41',
    authDomain: 'contacts-app-6ea41.firebaseapp.com',
    storageBucket: 'contacts-app-6ea41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAopHVgjHBSLtZpx7-4Xd6hATGm2cdLUIw',
    appId: '1:600457489084:android:23a88da244e7b3bc927eb9',
    messagingSenderId: '600457489084',
    projectId: 'contacts-app-6ea41',
    storageBucket: 'contacts-app-6ea41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXD2nZ04l43qXusgd6Okf7Q5LeaGruKs4',
    appId: '1:600457489084:ios:6bc85c8c948f3703927eb9',
    messagingSenderId: '600457489084',
    projectId: 'contacts-app-6ea41',
    storageBucket: 'contacts-app-6ea41.appspot.com',
    iosBundleId: 'com.example.contact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXD2nZ04l43qXusgd6Okf7Q5LeaGruKs4',
    appId: '1:600457489084:ios:7a50f485d4c71968927eb9',
    messagingSenderId: '600457489084',
    projectId: 'contacts-app-6ea41',
    storageBucket: 'contacts-app-6ea41.appspot.com',
    iosBundleId: 'com.example.contact.RunnerTests',
  );
}
